name: Deploy via SFTP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key manual
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 21 nanhoniatravel.com >> ~/.ssh/known_hosts

      - name: Deploy files via SFTP
        run: |
          sftp -o StrictHostKeyChecking=no -P 21 travel@nanhoniatravel.com << 'EOF'
          put -r * /
          bye
          EOF
