name: Deploy via FTPS Robust

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar FTP Deploy FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: 21
          protocol: ftps
          security: loose             # Ignora certificado inválido, mas mantém TLS
          server-dir: /               # Pasta destino no servidor
          local-dir: ./               # Pasta local a subir
          dry-run: false              # Se true, só simula o deploy
          dangerous-clean-slate: true # Limpa o que tem no servidor antes do upload (cuidado!)
          git-ftp-args: --verbose     # Mais detalhes no log

      - name: Finalizar
        run: echo "Deploy FTPS concluído com sucesso!"
