name: Deploy via FTPS com lftp

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via lftp FTPS
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
        run: |
          lftp -u "$FTP_USER","$FTP_PASS" -p 21 ftps://$FTP_HOST <<EOF
            set ftp:ssl-force true          # Força usar TLS
            set ftp:ssl-protect-data true   # Protege canal de dados
            set ssl:verify-certificate no   # Ignora erro certificado
            mirror -R --delete ./ /         # Upload recursivo, apaga arquivos removidos
            quit
          EOF

      - name: Finalizar
        run: echo "Deploy FTPS via lftp concluído com sucesso!"
