name: Deploy via SFTP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SFTP_PRIVATE_KEY }}

      - name: Deploy files via SFTP
        run: |
          sftp -o StrictHostKeyChecking=no -P 21 travel@nanhoniatravel.com << 'EOF'
          put -r * /
          bye
          EOF
